apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-app
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  source:
    repoURL: https://github.com/TeyDzh/argocd-redis.git
    targetRevision: HEAD
    chart: rabbitmq
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
