apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-app
spec:
  project: default
  source:
    chart: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.0.0
    helm:
      releaseName: rabbitmq
      parameters:
        - name: podAntiAffinity
          value: app
        - name: podAntiAffinity
          value: In
        - name: podAntiAffinity
          value: rabbitmq
        - name: podAntiAffinity
          value: kubernetes.io/hostname
        - name: nodeAffinity
          value: rabbitmq-node
        - name: nodeAffinity
          value: In
        - name: nodeAffinity
          value: "true"
        - name: replicaCount
          value: "6"
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
