apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-app
spec:
  project: default
  source:
    chart: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.0.0
    helm:
      releaseName: rabbitmq
      values: |
        replicaCount: 2
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rabbitmq
                topologyKey: "kubernetes.io/hostname"
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: rabbitmq-node
                      operator: In
                      values:
                        - "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
