apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-redis-app
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbit-redis-app
  source:
    repoURL: https://github.com/TeyDzh/argocd-redis.git
    targetRevision: HEAD
    path: dep
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
  sourceHelm:
    valuesFiles:
      - redis.yaml
      - rabbit.yaml
