---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-app
  namespace: argo
spec:
  project: default
  source:
    chart: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.0.0
    helm:
      releaseName: rabbitmq
      values: |
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
        persistence:
          enabled: false
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - minikube
                        - minikube-m02
                        - minikube-m03
        replicas: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
