---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
  namespace: argo
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.11.3
    helm:
      # parameters:
      #   - name: replica.replicaCount
      #     value: "3"
      releaseName: redis
      values: |
        replica:
          replicaCount: 3
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
        persistence:
          enabled: false
        auth:
          enable: false
        commonConfiguration: |-
          appendonly no
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - minikube
                        - minikube-m02
                        - minikube-m03
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
