apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.11.3
    helm:
      releaseName: redis
      parameters:
        - name: podAntiAffinity
          value: app
        - name: podAntiAffinity
          value: In
        - name: podAntiAffinity
          value: redis
        - name: podAntiAffinity
          value: kubernetes.io/hostname
        - name: nodeAffinity
          value: redis-node
        - name: nodeAffinity
          value: In
        - name: nodeAffinity
          value: "true"
        - name: replicaCount
          value: "6"
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
