apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
spec:
  project: default
  source:
    chart: bitnami/redis
    targetRevision: 17.11.3
    repoURL: https://github.com/bitnami/charts.git
    helm:
      releaseName: reddis
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
