apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  source:
    repoURL: https://github.com/TeyDzh/argocd-redis.git
    targetRevision: HEAD
    chart: redis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - redis
        topologyKey: "kubernetes.io/hostname"
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: redis-node
                  operator: In
                  values:
                    - "true"
