apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.6.1
    helm:
      releaseName: redis
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
