apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-argo-app
  namespace: argo
spec:
  project: default

  source:
    repoURL: git@github.com:TeyDzh/terra.git
    targetRevision: HEAD
    path: dep 
  destination:
    server: https://kubernetes.default.svc
    namespace: redis

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true

                
