apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: redis
    version: latest
  values:
    replica:
      enabled: true
      replicas: 2
    persistence:
      enabled: false
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - redis
        topologyKey: "kubernetes.io/hostname"
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: redis-node
                operator: In
                values:
                  - "true"
